# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  # - osx
julia:
  - 1.0
  - 1.1
  - nightly
matrix:
  allow_failures:
    - julia: nightly
  fast_finish: true
notifications:
  email: false

# Do not build my PR twice.  Use the build on branch.
# https://github.com/travis-ci/travis-ci/issues/1147#issuecomment-76296437
if: NOT (type == pull_request AND repo == tkf/BangBang.jl)

install:
  - unset JULIA_PROJECT
  - julia -e 'using Pkg; pkg"add https://github.com/tkf/Run.jl"'
  - julia -e 'using Run; Run.prepare_test()'
script:
  - julia -e 'using Run; Run.test(inline=false)'
after_success:
  - julia -e 'using Run; Run.after_success_test()'
jobs:
  include:
    - stage: Documentation
      julia: 1.1
      script: julia --project=docs --color=yes -e '
          using Pkg;
          Pkg.develop(PackageSpec(path=pwd()));
          Pkg.instantiate();
          include("docs/make.jl");'
      after_success: skip
